// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Phone  *string  `json:"phone,omitempty"`
	Orders []*Order `json:"orders,omitempty"`
}

type Food struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

type Invoice struct {
	ID            string  `json:"id"`
	Order         *Order  `json:"order"`
	TotalAmount   float64 `json:"totalAmount"`
	PaymentStatus string  `json:"paymentStatus"`
	IssuedAt      string  `json:"issuedAt"`
}

type Mutation struct {
}

type Order struct {
	ID        string    `json:"id"`
	Customer  *Customer `json:"customer"`
	FoodItems []*Food   `json:"foodItems"`
	Total     float64   `json:"total"`
	Status    string    `json:"status"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

type Query struct {
}
